#!/bin/bash

# smat2mtx smatfile
# Convert an smatfile into an mtx file


die () {
    echo >&2 "$@"
    exit 1
}

INPUT=$1
[ -e $INPUT ] || die "input file $INPUT does not exist" 

BASENAME=${INPUT%.*} # strip off the extension if present
OUTPUT=$BASENAME.mtx

>$OUTPUT
echo "%%MatrixMarket matrix coordinate real general" >> $OUTPUT
echo "% Generated `date`" >> $OUTPUT
awk '{if(NR==1) print $1" "$2" "$3; else print $1+1" "$2+1" "$3;}' $INPUT >> $OUTPUT
